openapi: "3.0.0"
info:
  title: User Model Backend API
  description: swagger docs for the API
  version: 1.1.0
  contact:
    email: mehadihasan968@gmail.com
    url: "https://github.com/mehediasif"

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemas:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      tags:
        - Home
      summary: returns a greeting message
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: string
                example: "myString"
        400:
          description: Bad Request
        500:
          description: internet Server Error